version: '3'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=coursera
    ports:
      - '3306:3306'
    volumes:
      - './pkg/repo/mysql/users.sql:/docker-entrypoint-initdb.d/items.sql'
  memcached:
    image: 'memcached:latest'
    ports:
      - '11211:11211'
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq'
    ports:
      - '5672:5672'
  mongodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=coursera
    ports:
      - '27017-27019:27017-27019'
  adminer:
    image: adminer
    restart: always
    links:
        - "mysql:mysql"
    ports:
      - 8090:8080

